version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./back-end:/srv/app
      #- /srv/app/node_modules
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

  app2:
    build:
      context: ./front-end
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front-end/:/front-end/
    ports:
      - 3000:3000
    depends_on:
      - strapi
    image: app2:react
    container_name: react_container
    command: npm start
